[settings]
# Define the selected format for the output
selected_format = "css"

# Specify the input directory of the JSON files
input_dir = "resources"

# Specify the input files
input_files = [
    "Colors.json",
    "StyleTokens.json",
    "ComponentTokens.json",
]

[css]
# A prefix to add to each generated CSS variable
prefix = "mw"

# Generate css as a TailwindCSS file
tailwindcss = true

# Include comments in the generated css
include_comments = true

# Use reserved keywords

# Specify the output file for the generated css
output = { dir = "output", file = "global.css" }

[logging]
# Define the log level for the application (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level = "DEBUG"
