[settings]
selected_format = "css"

[css]
prefix = "mw"
# Generate css as a TailwindCSS file
tailwindcss = true
discard_comments = false

# Specify the output file for the generated css
output = { dir = "", output = "generated.css" }

# Specify input JSON file(s) to generate css from
input = [
    { dir = "resources", input = "Colors.json" },
    { dir = "resrouces", input = "StyleTokens.json" },
    { dir = "resources", input = "SpacingTokens.json" },
    { dir = "resources", input = "ComponentTokens.json" },
]

[logging]
level = "DEBUG"
